/*
 * Copyright 2019-2026 Ossum Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.ossuminc.riddl.passes

import com.ossuminc.riddl.utils.*
import com.ossuminc.riddl.language.AST.*
import com.ossuminc.riddl.language.{AST, At, Messages}
import com.ossuminc.riddl.language.{Contents, *}
import com.ossuminc.riddl.passes.PassCreator
import com.ossuminc.riddl.passes.resolve.{ReferenceMap, ResolutionOutput, ResolutionPass, Usages}
import com.ossuminc.riddl.passes.symbols.{SymbolsOutput, SymbolsPass}
import com.ossuminc.riddl.passes.stats.StatsPass
import com.ossuminc.riddl.passes.validate.{ValidationOutput, ValidationPass}
import com.ossuminc.riddl.passes.analysis.{
  EntityLifecyclePass,
  MessageFlowPass,
  UseCaseTracePass,
  UseCaseWitnessPass
}

import scala.annotation.unused
import scala.collection.mutable
import scala.util.control.NonFatal

/** A function type that creates a Pass instance */
type PassCreator = (PassInput, PassesOutput) => Pass

/** A sequence of PassCreator. This is used to run a set of passes */
type PassCreators = Seq[PassCreator]

/** Base trait for options classes that are needed by passes */
trait PassOptions

/** Companion for [[PassOptions]], providing the do-nothing instance.
  *
  * Most passes need no options at all, so `empty` is the usual argument rather than a fallback for
  * a missing one — passing it is a statement that the pass is not configurable, not that its
  * configuration was omitted.
  */
object PassOptions {
  val empty: PassOptions = new PassOptions {}
}

/** Information a pass must provide, basically its name and a function to create the pass
  */
trait PassInfo[OPT <: PassOptions] {

  /** The name of the pass */
  def name: String

  /** A function to create an instance of the pass
    *
    * @param options
    *   The options the pass requires
    * @return
    */
  def creator(options: OPT)(using pc: PlatformContext): PassCreator
}

/** The kinds of nodes that can be at the root of a pass. */
type PassRoot = Branch[?]

/** Information that a Pass must produce, currently just any messages it generated. Passes should
  * derive their own concrete PassOutput classes from this trait
  */
trait PassOutput {

  /** The new [[com.ossuminc.riddl.language.AST.Root]] of the model, if the [[Pass]] modified it in
    * [[Pass.preProcess()]]
    */
  def root: PassRoot

  /** Any [[com.ossuminc.riddl.language.Messages.Messages]] that were generated by the pass */
  def messages: Messages.Messages
}

/** Companion for [[PassOutput]], providing an output carrying an empty [[Root]] and no messages.
  *
  * Note `empty` is a `def`, not a `val`: it builds a fresh instance per call. Nothing depends on
  * distinct identity today, but a shared mutable-looking singleton for a type that carries a whole
  * AST is a poor default.
  */
object PassOutput {
  def empty: PassOutput = new PassOutput {
    val root: PassRoot = Root.empty
    val messages: Messages.Messages = Messages.empty
  }
}

/** The input to a Pass in order to do its work. This consists of just the parsed model and the
  * common options. Passes cannot extend this.
  * @param root
  *   The result of the parsing run, consisting of the RootContainer from which all AST content can
  *   be reached
  */
case class PassInput(
  root: PassRoot,
  parseMessages: Messages.Messages = Messages.empty
)

/** Companion for [[PassInput]], providing an input over an empty [[Root]].
  *
  * Useful as the starting point for a pass chain that has parsed nothing — a pass run over it
  * produces no messages rather than failing, which is what lets the "no input" case travel the
  * same code path as every other.
  */
object PassInput {
  val empty: PassInput = PassInput(Root.empty)
}

/** The output from running a set of Passes. This collects the PassOutput instances from each Pass
  * run and provides utility messages for getting that information.
  */
case class PassesOutput() {

  private val outputs: mutable.HashMap[String, PassOutput] = mutable.HashMap.empty

  def getAllMessages: Messages.Messages = {
    outputs.values.foldLeft(Messages.empty) { case (prior, current) =>
      prior.appendedAll(current.messages)
    }
  }

  def outputOf[T <: PassOutput](passName: String): Option[T] = {
    outputs.get(passName).map(_.asInstanceOf[T])
  }

  def outputIs(passName: String, output: PassOutput): Unit = {
    outputs.put(passName, output)
  }

  def hasPassOutput(passName: String): Boolean = {
    outputs.contains(passName)
  }

  lazy val messages: Messages.Messages = getAllMessages

  lazy val symbols: SymbolsOutput =
    outputOf[SymbolsOutput](SymbolsPass.name).getOrElse(SymbolsOutput())
  lazy val resolution: ResolutionOutput =
    outputOf[ResolutionOutput](ResolutionPass.name).getOrElse(ResolutionOutput())
  lazy val validation: ValidationOutput =
    outputOf[ValidationOutput](ValidationPass.name).getOrElse(ValidationOutput())

  def refMap: ReferenceMap = resolution.refMap
  def usage: Usages = resolution.usage

}

/** The result of running a set of passes. This provides the input and outputs of the run as well as
  * any additional messages (likely from an exception). This provides convenience methods for
  * accessing the various output content
  *
  * @param input
  *   The input provided to the run of the passes
  * @param outputs
  *   The PassesOutput collected from teh run of the Passes
  * @param additionalMessages
  *   Any additional messages, likely from an exception or other unusual circumstance.
  */
case class PassesResult(
  input: PassInput = PassInput.empty,
  outputs: PassesOutput = PassesOutput(),
  additionalMessages: Messages.Messages = Messages.empty
) {
  def root: PassRoot = input.root

  /** Get the output of one pass that ran
    *
    * @param passName
    *   The name of the pass. Use the Pass's companion object's [[PassInfo.name]] method to retrieve
    *   it.
    * @tparam T
    *   The type of the Pass's output which must derive from [[PassOutput]].
    * @return
    */
  def outputOf[T <: PassOutput](passName: String): Option[T] = outputs.outputOf[T](passName)
  def hasOutputOf(passName: String): Boolean = outputs.hasPassOutput(passName)

  lazy val messages: Messages.Messages = outputs.messages ++ additionalMessages
  lazy val symbols: SymbolsOutput = outputs.symbols
  lazy val resolution: ResolutionOutput = outputs.resolution
  lazy val validation: ValidationOutput = outputs.validation

  def refMap: ReferenceMap = resolution.refMap
  def usage: Usages = resolution.usage
}

/** Companion for [[PassesResult]], providing the result of having run no passes at all.
  *
  * Distinct from a result whose passes ran and produced nothing: both are message-free, and only
  * the caller knows which it asked for. Do not use `empty` to stand in for a FAILED run — a
  * failure carries its messages, and discarding them here is how a failure becomes a silent
  * success.
  */
object PassesResult {
  val empty: PassesResult = PassesResult()
}

/** Abstract Pass definition.
  * @param in
  *   The input to the pass. This provides the data over which the pass is executed
  * @param out
  *   The output from previous runs of OTHER passes, which is a form of input to the pass, perhaps.
  * @param withIncludes
  *   When true, Include nodes are treated as regular containers:
  *   - process() is called for the Include node itself
  *   - Include is pushed onto the parent stack
  *   - Include appears in the parent hierarchy
  *
  * When false (default), Include nodes are transparent:
  *   - Include contents are traversed directly
  *   - Include does NOT appear in parent stack
  *   - Include is semantically invisible to the pass
  *
  * WARNING: Setting this to true breaks semantic transparency of Include nodes. Only use when you
  * need to preserve Include structure (e.g., serialization, AST transformation). DO NOT use for
  * passes that perform path resolution or reference lookup - these depend on Include being
  * transparent to maintain correct naming hierarchy.
  *
  * Example usage:
  * {{{
  *   // For serialization that must preserve Include nodes:
  *   case class BASTWriter(...) extends Pass(input, outputs, withIncludes = true)
  *
  *   // For normal passes (default - Include is transparent):
  *   case class ValidationPass(...) extends Pass(input, outputs)
  * }}}
  */
abstract class Pass(
  @unused val in: PassInput,
  val out: PassesOutput,
  protected val withIncludes: Boolean = false
)(using io: PlatformContext) {

  /** The messages collected during the pass */
  protected val messages: Messages.Accumulator = Messages.Accumulator()

  /** The name of the pass for inclusion in messages it produces. This must be implemented by the
    * subclass
    * @return
    *   A string value giving the name of this pass
    */
  def name: String

  /** If your pass requires the output from other passes, call this function from your pass's
    * constructor. It will ensure that your pass will fail construction if the input doesn't contain
    * that required pass's output.
    * @param passInfo
    *   The pass's companion object from which this function will obtain the pass's name
    */
  protected final def requires[OPT <: PassOptions](passInfo: PassInfo[OPT]): Unit = {
    require(
      out.hasPassOutput(passInfo.name),
      s"Required pass '${passInfo.name}' was not run prior to '$name'"
    )
  }

  /** Pre-process the root before actually traversing. This is also a signal that the processing is
    * about to start.
    * @param root
    *   A [[com.ossuminc.riddl.language.AST.Root]] node which encapsulates the whole model. This is
    *   the state of the Root as of the last pass.
    * @return
    *   Typically returns the same Root objects with changes in subsequent levels, but it entirely
    *   possibly to completely reorganize the hierarchy, including its root node.
    */
  def preProcess(root: PassRoot): PassRoot = root

  /** The main implementation of the Pass. The AST is walked in a depth first manner calling this
    * function for each definition it encounters.
    *
    * @param definition
    *   The definition to be processed
    * @param parents
    *   The stack of definitions that are the parents of
    *   [[com.ossuminc.riddl.language.AST.Definition]]. This stack goes from immediate parent
    *   towards the root. The root is deepest in the stack.
    */
  protected def process(
    definition: RiddlValue,
    parents: ParentStack
  ): Unit

  /** A signal that the processing is complete and no more calls to `process` will be made. This
    * also gives the Pass subclass a chance to do post-processing as some computations can only be
    * done after collecting data from the entire AST
    *
    * @param root
    *   The root of the parsed model just as a convenience for post-processing
    */
  def postProcess(root: PassRoot): Unit = ()

  /** Generate the output of this Pass. This will only be called after all the calls to process have
    * completed.
    * @param root
    *   The new [[com.ossuminc.riddl.language.AST.Root]] of the model that the pass computed
    * @return
    *   an instance of the output type
    */
  def result(root: PassRoot): PassOutput

  /** Close any resources used so this can be used with AutoCloseable or Using.Manager
    */
  def close(): Unit = ()

  /** A method for the traversal of the AST hierarchy. While subclasses implement this differently,
    * there is generally no need to override in non-RIDDL code. This implementation is width first
    *
    * @param definition
    *   The root (starting point) of the traversal
    * @param parents
    *   The parents of the definition
    */
  protected def traverse(definition: RiddlValue, parents: ParentStack): Unit = {
    definition match {
      case root: Root =>
        process(root, parents)
        parents.push(root)
        root.contents.foreach { value => traverse(value, parents) }
        parents.pop()
      case include: Include[?] =>
        if withIncludes then
          // Process the Include node itself, but don't add to parent stack
          // Include contents logically belong to the parent container, not the Include
          process(include, parents)
          include.contents.foreach { value => traverse(value, parents) }
        else
          // NOTE: no push/pop here because include is an unnamed container and does not participate in parent stack
          include.contents.foreach { value => traverse(value, parents) }
        end if
      case sagaStep: SagaStep =>
        // MUST precede `case leaf: Leaf`. A SagaStep is a Leaf whose statements live in the
        // `doStatements`/`undoStatements` FIELDS rather than in `contents`, so the Leaf case
        // below processes the step and never descends -- which meant saga statements were
        // never resolved and never reached `validateStatement`. A saga step could name
        // definitions that do not exist and validate completely clean.
        //
        // NO push/pop, deliberately: `ParentStack.push` takes a `Branch[?]` and a SagaStep is
        // a Leaf, so it cannot be pushed without making it a Branch. Traversing without
        // pushing is exactly what Include and BASTImport do above -- their contents
        // "logically belong to the parent container" -- and it is also RIGHT here:
        // `parents.head` stays the Saga, which is the correct resolution scope for a step's
        // statements and is a Branch as `type Parents = Seq[Branch[?]]` requires.
        process(sagaStep, parents)
        sagaStep.doStatements.foreach { value => traverse(value, parents) }
        sagaStep.undoStatements.foreach { value => traverse(value, parents) }
      // The three statements that HOLD statements in FIELDS. Each MUST precede `case leaf: Leaf`,
      // for exactly the reason SagaStep does: a Statement is a Leaf, so without these the nested
      // body is never traversed and every reference inside it is never resolved and never
      // validated -- a model naming definitions that do not exist validates clean. Verified with a
      // repro on 2026-08-14: a bogus `tell` at the top of a clause was reported, the same `tell`
      // one level inside `when … then { … } end` was silent.
      //
      // NO push: a Statement is not a Branch and cannot be pushed, and the enclosing clause is
      // already the correct resolution scope for a nested statement -- the same reasoning, and the
      // same consequence for `parents.head`, as SagaStep above.
      //
      // `HierarchyPass` deliberately does NOT need this: it overrides `traverse` and its visitors
      // emit field-held statements themselves, in the position the syntax requires.
      case whenStmt: WhenStatement =>
        process(whenStmt, parents)
        whenStmt.thenStatements.foreach { value => traverse(value, parents) }
        whenStmt.elseStatements.foreach { value => traverse(value, parents) }
      case matchStmt: MatchStatement =>
        process(matchStmt, parents)
        matchStmt.cases.foreach { mc => mc.statements.foreach { v => traverse(v, parents) } }
        matchStmt.default.foreach { value => traverse(value, parents) }
      case foreachStmt: ForeachStatement =>
        process(foreachStmt, parents)
        foreachStmt.doStatements.foreach { value => traverse(value, parents) }
      case leaf: Leaf =>
        process(leaf, parents)
      case correlation: Correlation =>
        // A70. MUST precede `case branch: Branch[?]` for the same reason SagaStep precedes `Leaf`
        // above: a Correlation's timeout statements live in the `timeoutStatements` FIELD, not in
        // `contents`, so the generic Branch arm would traverse its handler and silently skip them
        // -- and a `tell` in an unreached block resolves nothing, naming definitions that need not
        // exist while the model validates clean. Unlike SagaStep, a Correlation IS a Branch, so it
        // is pushed: it is the right resolution scope for both its folds and its timeout block.
        process(correlation, parents)
        parents.push(correlation)
        correlation.contents.foreach { (value: RiddlValue) => traverse(value, parents) }
        correlation.timeoutStatements.foreach { (value: RiddlValue) => traverse(value, parents) }
        parents.pop()
      case oic: OnInitializationClause =>
        // Task 3, same shape as Correlation above and for the same reason: `parameters` lives in
        // a FIELD, not `contents`, so the generic Branch arm below would walk the clause's body
        // and silently skip its parameter list -- their types would never be resolved and never
        // validated, so a parameter naming a type that doesn't exist would validate clean.
        process(oic, parents)
        parents.push(oic)
        oic.parameters.foreach { (value: RiddlValue) => traverse(value, parents) }
        oic.contents.foreach { (value: RiddlValue) => traverse(value, parents) }
        parents.pop()
      case otc: OnTerminationClause =>
        process(otc, parents)
        parents.push(otc)
        otc.parameters.foreach { (value: RiddlValue) => traverse(value, parents) }
        otc.contents.foreach { (value: RiddlValue) => traverse(value, parents) }
        parents.pop()
      case branch: Branch[?] =>
        process(branch, parents)
        parents.push(branch)
        branch.contents.foreach { (value: RiddlValue) => traverse(value, parents) }
        parents.pop()
      case value: RiddlValue =>
        // NOTE: everything else is just a non-definition non-container
        process(value, parents)
    }
  }
}

/** A [[Pass]] that visits every node CHILDREN-FIRST.
  *
  * The contrast with the base [[Pass]] is the ORDER, not the coverage: a node's `process` runs
  * after its whole subtree has been processed, so a pass that must know what a container holds
  * before deciding anything about the container itself wants this one.
  *
  * **Do NOT use this to MUTATE contents during the walk.** `Container.flatten()` learned that the
  * hard way: removing `Include`/`BASTImport` wrappers while a depth-first traversal is iterating
  * corrupts the underlying `ArrayBuffer`, so it uses the base [[Pass]] instead. Depth-first is for
  * reading a tree bottom-up, not for rewriting one.
  *
  * Two traversal subtleties inherited from [[Pass]] and easy to trip over:
  *   - an [[Include]] is NOT pushed onto the parent stack, because its children belong to the
  *     ENCLOSING container — a pass that needs an include to be a scope must override `traverse`
  *     (`JsonifierPass` does exactly this);
  *   - the generic `Branch` arm walks `contents` ONLY, so a node holding children in a FIELD —
  *     `Correlation.timeoutStatements`, `SagaStep`'s do/undo blocks — needs its own case BEFORE
  *     that arm or those children are never visited, and the model validates clean while naming
  *     definitions that need not exist.
  *
  * @param input
  *   The input to the pass, providing the data over which it is executed
  * @param outputs
  *   The outputs of prior passes, which this pass may depend on
  * @param withIncludes
  *   Whether to descend into [[Include]] wrappers during traversal
  */
abstract class DepthFirstPass(
  input: PassInput,
  outputs: PassesOutput,
  withIncludes: Boolean = false
)(using pc: PlatformContext)
    extends Pass(input, outputs, withIncludes) {

  /** A method for the traversal of the AST hierarchy. This implementation traverses nodes in a
    * depth first fashion.
    *
    * @param definition
    *   The root (starting point) of the traversal
    * @param parents
    *   The parents of the definition
    */
  override protected def traverse(definition: RiddlValue, parents: ParentStack): Unit = {
    definition match {
      case root: Root =>
        parents.push(root)
        root.contents.foreach { value => traverse(value, parents) }
        parents.pop()
        process(root, parents)
      case include: Include[?] =>
        // Depth-first: process children first, then parent
        // NOTE: no push/pop here because include is an unnamed container and does not participate in parent stack
        include.contents.foreach { value => traverse(value, parents) }
        process(include, parents)
      case leaf: Leaf =>
        process(leaf, parents)
      case branch: Branch[?] =>
        parents.push(branch)
        branch.contents.foreach { (value: RiddlValue) => traverse(value, parents) }
        parents.pop()
        process(branch, parents)
      case value: RiddlValue =>
        // NOTE: everything else is just a non-definition non-container
        process(value, parents)
    }
  }

}

/** A Pass base class that allows the processing to be done based on containers, and calling these
  * methods:
  *   - openContainer at the start of container's processing
  *   - processLeaf for any leaf nodes within the container
  *   - processValue for any non-definitions within the container
  *   - closeContainer after all the container's contents have been processed
  *   - openInclude for encountering an include statement
  *   - closeInclude for completing the included content
  *
  * This kind of Pass allows the processing to follow the AST hierarchy so that container nodes can
  * run before all their content (openContainer) and also after all its content (closeContainer).
  * This is necessary for passes that must maintain the hierarchical structure of the AST model in
  * their processing.
  *
  * @param input
  *   The PassInput to process
  * @param outputs
  *   The outputs of previous passes in case this pass needs it
  */
abstract class HierarchyPass(
  input: PassInput,
  outputs: PassesOutput,
  withIncludes: Boolean = false
)(using PlatformContext)
    extends Pass(input, outputs, withIncludes) {

  /** not required in this kind of pass, final override it as a result
    *
    * @param definition
    *   The definition to be processed
    * @param parents
    *   The stack of definitions that are the parents of
    *   [[com.ossuminc.riddl.language.AST.Definition]]. This stack goes from immediate parent
    *   towards the root. The root is deepest in the stack.
    */
  override final def process(definition: RiddlValue, parents: ParentStack): Unit = ()

  /** Called by traverse when a new container is started Subclasses must implement this method.
    * @param definition
    *   The definition that was opened
    * @param parents
    *   The parents of the definition opened
    */
  protected def openContainer(definition: Definition, parents: Parents): Unit

  /** Called by traverse when a leaf node is encountered Subclasses must implement this method
    * @param definition
    *   The leaf definition that was found
    * @param parents
    *   THe parents of the leaf node
    */
  protected def processLeaf(definition: Leaf, parents: Parents): Unit

  /** Process a non-definition, non-include, value
    *
    * @param value
    *   The value to be processed
    * @param parents
    *   The parent definitions of value
    */
  protected def processValue(value: RiddlValue, parents: Parents): Unit

  protected def openInclude(include: Include[?], parents: Parents): Unit = ()
  protected def closeInclude(include: Include[?], parents: Parents): Unit = ()

  /** Called by traverse after all leaf nodes of an opened node have been processed and the opened
    * node is now being closed. Subclasses must implement this method.
    * @param definition
    *   The opened node that now needs to be closed
    * @param parents
    *   THe parents of the node to be closed; should be the same as when it was opened
    */
  protected def closeContainer(definition: Definition, parents: Parents): Unit

  /** Redefine traverse to make the three calls
    *
    * @param definition
    *   The RiddlValue being considered
    * @param parents
    *   The definition parents of the value
    */
  /** Controls whether BASTImport contents are traversed. Override in subclasses to suppress content
    * traversal (e.g., when emitting an import directive instead of inlining the imported content).
    * @return
    *   true to traverse BASTImport contents, false to skip
    */
  protected def traverseBASTImportContents(bi: BASTImport): Boolean = true

  protected def openBASTImport(bi: BASTImport, parents: Parents): Unit = ()
  protected def closeBASTImport(bi: BASTImport, parents: Parents): Unit = ()

  override protected def traverse(definition: RiddlValue, parents: ParentStack): Unit = {
    definition match {
      case include: Include[?] => // treat includes specially
        val def_parents = parents.toParents
        openInclude(include, def_parents)
        // Never add Include to parent stack - contents logically belong to parent container
        // HierarchyPass always calls openInclude/closeInclude to give subclasses visibility
        include.contents.foreach { item => traverse(item, parents) }
        closeInclude(include, def_parents)
      case bastImport: BASTImport => // treat BASTImport like Include
        val def_parents = parents.toParents
        openBASTImport(bastImport, def_parents)
        if traverseBASTImportContents(bastImport) then
          bastImport.contents.foreach { item => traverse(item, parents) }
        end if
        closeBASTImport(bastImport, def_parents)
      case container: Branch[?] => // must be a container so descend
        val def_parents = parents.toParents // save this for the closeContainer below
        openContainer(container, def_parents)
        if container.contents.nonEmpty
        then // just optimize out the push/pop for empty contents, which is frequent
          parents.push(container)
          container.contents.foreach(item => traverse(item, parents)) // recurse!
          parents.pop()
        end if
        closeContainer(container, def_parents)
      case leaf: Leaf => // no further descent
        processLeaf(leaf, parents.toParents)
      case value: RiddlValue => // no further descent
        processValue(value, parents.toParents)
    }
  }
}

/** The Visitor definition for the [[VisitingPass]]. You must implement all the methods of this
  * class and pass it to the [[VisitingPass]]
  */
trait PassVisitor:
  // Open for each Container Definition
  def openType(typ: Type, parents: Parents): Unit
  def openModule(module: Module, parents: Parents): Unit
  def openDomain(domain: Domain, parents: Parents): Unit
  def openContext(context: Context, parents: Parents): Unit
  def openEntity(entity: Entity, parents: Parents): Unit
  def openAdaptor(adaptor: Adaptor, parents: Parents): Unit
  def openEpic(epic: Epic, parents: Parents): Unit
  def openUseCase(uc: UseCase, parents: Parents): Unit
  def openFunction(function: Function, parents: Parents): Unit
  def openSaga(saga: Saga, parents: Parents): Unit
  def openStreamlet(streamlet: Streamlet, parents: Parents): Unit
  def openRepository(repository: Repository, parents: Parents): Unit
  def openProjector(projector: Projector, parents: Parents): Unit
  def openHandler(handler: Handler, parents: Parents): Unit
  def openOnClause(onClause: OnClause, parents: Parents): Unit
  def openGroup(group: Group, parents: Parents): Unit
  def openOutput(output: Output, parents: Parents): Unit
  def openInput(input: Input, parents: Parents): Unit
  def openState(state: State, parents: Parents): Unit
  def openCorrelation(correlation: Correlation, parents: Parents): Unit
  def openInclude(include: Include[?], parents: Parents): Unit
  def openBASTImport(bi: BASTImport, parents: Parents): Unit

  // Close for each type of container definition
  def closeType(typ: Type, parents: Parents): Unit
  def closeModule(module: Module, parents: Parents): Unit
  def closeDomain(domain: Domain, parents: Parents): Unit
  def closeContext(context: Context, parents: Parents): Unit
  def closeEntity(entity: Entity, parents: Parents): Unit
  def closeAdaptor(adaptor: Adaptor, parents: Parents): Unit
  def closeEpic(epic: Epic, parents: Parents): Unit
  def closeUseCase(uc: UseCase, parents: Parents): Unit
  def closeFunction(function: Function, parents: Parents): Unit
  def closeSaga(saga: Saga, parents: Parents): Unit
  def closeStreamlet(streamlet: Streamlet, parents: Parents): Unit
  def closeRepository(repository: Repository, parents: Parents): Unit
  def closeProjector(projector: Projector, parents: Parents): Unit
  def closeHandler(handler: Handler, parents: Parents): Unit
  def closeOnClause(onClause: OnClause, parents: Parents): Unit
  def closeGroup(group: Group, parents: Parents): Unit
  def closeOutput(output: Output, parents: Parents): Unit
  def closeInput(input: Input, parents: Parents): Unit
  def closeState(state: State, parents: Parents): Unit
  def closeCorrelation(correlation: Correlation, parents: Parents): Unit
  def closeInclude(include: Include[?], parents: Parents): Unit
  def closeBASTImport(bi: BASTImport, parents: Parents): Unit

  // LeafDefinitions
  def doField(field: Field): Unit
  def doMethod(method: Method): Unit
  def doAuthor(author: Author): Unit
  def doConstant(constant: Constant): Unit
  def doInvariant(invariant: Invariant): Unit
  def doVersion(version: Version): Unit
  def doCopyright(copyright: Copyright): Unit
  def doSagaStep(sagaStep: SagaStep): Unit
  def doInlet(inlet: Inlet): Unit
  def doOutlet(outlet: Outlet): Unit
  def doConnector(connector: Connector): Unit
  def doUser(user: User): Unit
  def doSchema(schema: Schema): Unit
  def doRelationship(relationship: Relationship): Unit
  def doEnumerator(enumerator: Enumerator): Unit
  def doContainedGroup(containedGroup: ContainedGroup): Unit

  // Non Definition values
  def doComment(comment: Comment): Unit
  def doAuthorRef(reference: AuthorRef): Unit
  def doBriefDescription(brief: BriefDescription): Unit
  def doDescription(description: Description): Unit
  def doStatement(statement: Statements): Unit
  def doInteraction(interaction: Interaction): Unit
  def doOptionValue(optionValue: OptionValue): Unit

  /** A [[Function]]'s or [[Saga]]'s `requires`/`returns` clause. These are content rather than
    * fields on their container, so a visitor sees them in the position the author wrote them —
    * which is the whole point of the move, since a comment may now sit above or between them.
    */
  def doRequires(requires: Requires): Unit
  def doReturns(returns: Returns): Unit

  /** A [[Group]]'s or [[Epic]]'s `shown by { <url>… }` clause.
    *
    * Same shape as `requires`/`returns` above: it is CONTENT, so a visitor must see it in the
    * position the author wrote it. It had no hook until 2026-08-14 and was skipped outright by
    * `processValue`, on the reasoning that its holder reads it -- true of every visitor except the
    * one that has to write source back out, so prettify deleted every `shown by` it was given.
    */
  def doShownBy(shownBy: ShownBy): Unit

/** An abstract Pass that uses the Visitor pattern
  * (https://refactoring.guru/design-patterns/visitor)
  * @param input
  *   The PassInput to process
  * @param outputs
  *   The outputs of previous passes in case this pass needs it
  */
abstract class VisitingPass[VT <: PassVisitor](
  val input: PassInput,
  val outputs: PassesOutput,
  val visitor: VT
)(using PlatformContext)
    extends HierarchyPass(input, outputs):
  protected final def openContainer(container: Definition, parents: Parents): Unit =
    container match
      case typ: Type              => visitor.openType(typ, parents)
      case module: Module         => visitor.openModule(module, parents)
      case domain: Domain         => visitor.openDomain(domain, parents)
      case context: Context       => visitor.openContext(context, parents)
      case entity: Entity         => visitor.openEntity(entity, parents)
      case adaptor: Adaptor       => visitor.openAdaptor(adaptor, parents)
      case epic: Epic             => visitor.openEpic(epic, parents)
      case uc: UseCase            => visitor.openUseCase(uc, parents)
      case function: Function     => visitor.openFunction(function, parents)
      case saga: Saga             => visitor.openSaga(saga, parents)
      case streamlet: Streamlet   => visitor.openStreamlet(streamlet, parents)
      case repository: Repository => visitor.openRepository(repository, parents)
      case projector: Projector   => visitor.openProjector(projector, parents)
      case handler: Handler       => visitor.openHandler(handler, parents)
      case onClause: OnClause     => visitor.openOnClause(onClause, parents)
      case state: State           => visitor.openState(state, parents)
      case corr: Correlation      => visitor.openCorrelation(corr, parents)
      case group: Group           => visitor.openGroup(group, parents)
      case output: Output         => visitor.openOutput(output, parents)
      case input: Input           => visitor.openInput(input, parents)
      case _: Root                => () // ignore
      case _: Enumerator          => () // not a container
      case _: Field | _: Method | _: Term | _: Author | _: Constant | _: Invariant | _: SagaStep |
          _: Inlet | _: Outlet | _: Connector | _: User | _: Schema | _: Version | _: Copyright |
          _: GenericInteraction | _: SelfInteraction | _: VagueInteraction | _: ContainedGroup |
          _: Definition => // not containers
        () // not  containers
    end match
  end openContainer

  protected final def closeContainer(container: Definition, parents: Parents): Unit =
    container match
      case typ: Type              => visitor.closeType(typ, parents)
      case module: Module         => visitor.closeModule(module, parents)
      case domain: Domain         => visitor.closeDomain(domain, parents)
      case context: Context       => visitor.closeContext(context, parents)
      case entity: Entity         => visitor.closeEntity(entity, parents)
      case adaptor: Adaptor       => visitor.closeAdaptor(adaptor, parents)
      case epic: Epic             => visitor.closeEpic(epic, parents)
      case useCase: UseCase       => visitor.closeUseCase(useCase, parents)
      case function: Function     => visitor.closeFunction(function, parents)
      case saga: Saga             => visitor.closeSaga(saga, parents)
      case streamlet: Streamlet   => visitor.closeStreamlet(streamlet, parents)
      case repository: Repository => visitor.closeRepository(repository, parents)
      case projector: Projector   => visitor.closeProjector(projector, parents)
      case handler: Handler       => visitor.closeHandler(handler, parents)
      case onClause: OnClause     => visitor.closeOnClause(onClause, parents)
      case state: State           => visitor.closeState(state, parents)
      case corr: Correlation      => visitor.closeCorrelation(corr, parents)
      case group: Group           => visitor.closeGroup(group, parents)
      case output: Output         => visitor.closeOutput(output, parents)
      case input: Input           => visitor.closeInput(input, parents)
      case _: Root                => () // ignore
      case _: Field | _: Method | _: Term | _: Author | _: Constant | _: Invariant | _: SagaStep |
          _: Inlet | _: Outlet | _: Connector | _: User | _: Schema | _: Enumerator | _: Version |
          _: Copyright | _: GenericInteraction | _: SelfInteraction | _: VagueInteraction |
          _: ContainedGroup | _: Definition =>
        () // not  containers
    end match
  end closeContainer

  protected final def processLeaf(definition: Leaf, parents: Parents): Unit =
    definition match
      case field: Field                   => visitor.doField(field)
      case method: Method                 => visitor.doMethod(method)
      case author: Author                 => visitor.doAuthor(author)
      case constant: Constant             => visitor.doConstant(constant)
      case invariant: Invariant           => visitor.doInvariant(invariant)
      case version: Version               => visitor.doVersion(version)
      case copyright: Copyright           => visitor.doCopyright(copyright)
      case sagaStep: SagaStep             => visitor.doSagaStep(sagaStep)
      case inlet: Inlet                   => visitor.doInlet(inlet)
      case outlet: Outlet                 => visitor.doOutlet(outlet)
      case connector: Connector           => visitor.doConnector(connector)
      case user: User                     => visitor.doUser(user)
      case schema: Schema                 => visitor.doSchema(schema)
      case relationship: Relationship     => visitor.doRelationship(relationship)
      case containedGroup: ContainedGroup => visitor.doContainedGroup(containedGroup)
    end match
  end processLeaf

  protected final def processValue(value: RiddlValue, parents: Parents): Unit =
    value match
      case comment: Comment =>
        visitor.doComment(comment)
      case authorRef: AuthorRef =>
        visitor.doAuthorRef(authorRef)
      case brief: BriefDescription =>
        visitor.doBriefDescription(brief)
      case description: Description =>
        visitor.doDescription(description)
      case statement: Statement =>
        visitor.doStatement(statement)
      case interaction: Interaction =>
        visitor.doInteraction(interaction)
      case optionValue: OptionValue =>
        visitor.doOptionValue(optionValue)
      case enumerator: Enumerator =>
        visitor.doEnumerator(enumerator)
      case requires: Requires =>
        visitor.doRequires(requires)
      case returns: Returns =>
        visitor.doReturns(returns)
      case shownBy: ShownBy =>
        visitor.doShownBy(shownBy)
      // A Reference reaches here when it is a container's own field rather than a child of a
      // definition -- a Repository's RepositoryRef is the case that occurs. There is nothing for
      // a visitor to do with it: references are visited as part of the definition that holds
      // them, and resolution reads them from the refMap. Enumerated rather than absorbed by a
      // catch-all, so a value kind nobody anticipated fails loudly instead of being skipped.
      //
      // ShownBy sat in this arm until 2026-08-14, on the claim that its holder reads it. Every
      // visitor but one did; prettify has to WRITE it, and so dropped it from its output on every
      // group and epic that had one. The lesson is that "the holder reads it" is a statement about
      // the visitors that exist today, not a property of the node -- so it is a poor reason to
      // withhold a hook.
      case _: Reference[?] => ()
      case _ =>
        throw new IllegalStateException(
          s"processValue has no arm for ${value.getClass.getSimpleName} at ${value.loc}; add one " +
            "-- silently skipping it would drop the node from every visiting pass"
        )
    end match
  end processValue

  override protected final def openInclude(include: Include[?], parents: Parents): Unit =
    visitor.openInclude(include, parents)
  end openInclude

  override protected final def closeInclude(include: Include[?], parents: Parents): Unit =
    visitor.closeInclude(include, parents)
  end closeInclude

  override protected final def openBASTImport(bi: BASTImport, parents: Parents): Unit =
    visitor.openBASTImport(bi, parents)
  end openBASTImport

  override protected final def closeBASTImport(bi: BASTImport, parents: Parents): Unit =
    visitor.closeBASTImport(bi, parents)
  end closeBASTImport
end VisitingPass

/** An abstract PassOutput for use with passes that derive from CollectingPass. This just provides a
  * standard field name for the data that is collected, being `collected`.
  *
  * @param messages
  *   The required messages field from the PassOutput trait
  * @param collected
  *   The data that was collected from the CollectingPass's run
  * @tparam T
  *   The element type of the collected data
  */
abstract class CollectingPassOutput[T](
  root: Root = Root.empty,
  messages: Messages.Messages = Messages.empty,
  collected: Seq[T] = Seq.empty[T]
) extends PassOutput

/** A Pass subclass that processes the AST exactly the same as the depth first search that the Pass
  * class uses. The only difference is that
  *
  * @param input
  *   The PassInput to process
  * @param outputs
  *   The outputs from previous pass runs in case they are needed as input to this CollectingPass
  * @tparam ET
  *   The element type of the collected values
  */
abstract class CollectingPass[ET](input: PassInput, outputs: PassesOutput)(using PlatformContext)
    extends Pass(input, outputs) {

  /** The method usually called for each definition that is to be processed but our implementation
    * of traverse instead calls collect so a value can be returned. This implementation is final
    * because it is meant to be ignored.
    *
    * @param definition
    *   The definition to be processed
    * @param parents
    *   The stack of definitions that are the parents of
    *   [[com.ossuminc.riddl.language.AST.Definition]]. This stack goes from immediate parent
    *   towards the root. The root is deepest in the stack.
    */
  override final def process(definition: RiddlValue, parents: ParentStack): Unit = {
    val collected: Seq[ET] = collect(definition, parents)
    collectedValues ++= collected
  }

  protected val collectedValues: mutable.ArrayBuffer[ET] = mutable.ArrayBuffer.empty[ET]

  /** The processing method called at each node, similar to [[Pass.process]] but modified to return
    * a sequence of the collectable, [[ET]].
    *
    * @param definition
    *   The definition from which an [[ET]] value is collected.
    * @param parents
    *   The parents of the definition
    *
    * @return
    *   One of the collected values, an [[ET]]
    */
  protected def collect(definition: RiddlValue, parents: ParentStack): Seq[ET]

  override def result(root: PassRoot): CollectingPassOutput[ET]
}

/** A companion for Passes to provide entry points and other utilities of general interest */
object Pass {

  /** A PassCreators of the standard passes that should be run on every AST pass. These generate the
    * symbol table, resolve path references, and validate the input. Only after these three have
    * passed successful should the model be considered processable by other passes
    */
  def standardPasses(using PlatformContext): PassCreators =
    val base = Seq(SymbolsPass.creator(), ResolutionPass.creator(), ValidationPass.creator())
    // When completeness warnings are enabled, additionally run the A36 epic/use-case
    // analysis passes so their CompletenessWarnings surface in `riddlc validate`. These
    // are gated behind `showCompletenessWarnings` so that a plain `validate` (completeness
    // off) pays no extra pass cost. Prerequisites first: MessageFlowPass feeds
    // UseCaseWitnessPass; EntityLifecyclePass feeds UseCaseTracePass.
    if summon[PlatformContext].options.showCompletenessWarnings then
      base ++ Seq(
        MessageFlowPass.creator(),
        EntityLifecyclePass.creator(),
        UseCaseWitnessPass.creator(),
        UseCaseTracePass.creator()
      )
    else base
    end if
  end standardPasses

  /** Like standardPasses but uses Quick validation mode, skipping expensive streaming analysis and
    * handler classification. Suitable for interactive/LSP use where speed matters more than
    * exhaustive checks.
    */
  def quickValidationPasses(using PlatformContext): PassCreators =
    Seq(SymbolsPass.creator(), ResolutionPass.creator(), ValidationPass.quickCreator())

  /** A PassesCreate of the passes that extract information but don't do much real work. These
    * generate the symbol table, resolve path references, and calculate statistics. This allows
    * basic information be refreshed without doing a full validation
    */

  def informationPasses(using PlatformContext): PassCreators =
    Seq(SymbolsPass.creator(), ResolutionPass.creator(), StatsPass.creator())

  /** Run a set of passes against some input to obtain a result
    *
    * @param input
    *   The post-parsing input to the passes as a PassInput containing a Root
    * @param passes
    *   The list of Pass construction functions to use to instantiate the passes and run them. The
    *   type
    * @return
    *   A PassesResult which provides the individual
    */
  def runThesePasses(
    input: PassInput,
    passes: PassCreators
  )(using PlatformContext): PassesResult = {
    val outputs = PassesOutput()
    try {
      for pass <- passes yield {
        val aPass = pass(input, outputs)
        val output: PassOutput = runOnePass(input.root, aPass)
        outputs.outputIs(aPass.name, output)
      }
      // Carry any parse-time messages (warnings/deprecations) accumulated during
      // parsing into the result via additionalMessages so they surface to the user.
      PassesResult(input, outputs, input.parseMessages)
    } catch {
      case NonFatal(exception) =>
        // NEVER emit an empty message. `getRootCauseStackTrace` can render to nothing -- observed
        // for a ClassCastException thrown inside ResolutionPass, and earlier for a regex throwing
        // at class-initialisation under Scala Native (see the note at
        // DefinitionValidation.scala:451). Both surfaced as a bare `[severe] empty(1:1->1):` with
        // no text, no source line and no location, which says only "something threw somewhere".
        // ossum.tech spent about half an hour bisecting a model by hand to find one.
        //
        // This is the LAST-RESORT reporter for every in-pass exception, so whatever it prints is
        // all the author gets. `exception.toString` at minimum names the exception class and its
        // message, which is enough to start.
        val stackTrace = ExceptionUtils.getRootCauseStackTrace(exception).mkString("\n")
        val message =
          if stackTrace.trim.nonEmpty then stackTrace
          else
            val described = Option(exception.toString).map(_.trim).filter(_.nonEmpty)
            described.getOrElse(s"${exception.getClass.getName} (no message, no stack trace)")
        val messages: Messages.Messages = List(Messages.severe(message, At.empty))
        PassesResult(input, outputs, messages ++ input.parseMessages)
    }
  }

  /** Run the standard passes with the input provided */
  def runStandardPasses(
    input: PassInput
  )(using PlatformContext): PassesResult = {
    runThesePasses(input, standardPasses)
  }

  /** Run the standard passes on a Root */
  def runStandardPasses(
    model: Root
  )(using PlatformContext): PassesResult = {
    val input: PassInput = PassInput(model)
    runStandardPasses(input)
  }

  /** Run the information passes with the input provided */
  def runInformationPasses(input: PassInput)(using PlatformContext): PassesResult = {
    runThesePasses(input, informationPasses)
  }

  /** Run the information passes on a Root */
  def runInformationPasses(
    model: Root
  )(using PlatformContext): PassesResult = {
    val input: PassInput = PassInput(model)
    runInformationPasses(input)
  }

  /** Run the Symbols Pass */
  def runSymbols(input: PassInput, outputs: PassesOutput)(using PlatformContext): SymbolsOutput = {
    runPass[SymbolsOutput](input, outputs, SymbolsPass(input, outputs))
  }

  /** Run the Resolution Pass */
  def runResolution(input: PassInput, outputs: PassesOutput)(using
    PlatformContext
  ): ResolutionOutput = {
    runPass[ResolutionOutput](input, outputs, ResolutionPass(input, outputs))
  }

  /** Run the Validation pass */
  def runValidation(input: PassInput, outputs: PassesOutput)(using
    PlatformContext
  ): ValidationOutput = {
    runPass[ValidationOutput](input, outputs, ValidationPass(input, outputs))
  }

  /** Run an arbitrary pass */
  def runPass[OUT <: PassOutput](input: PassInput, outputs: PassesOutput, pass: Pass)(using
    PlatformContext
  ): OUT = {
    val output: OUT = Pass.runOnePass(input.root, pass).asInstanceOf[OUT]
    outputs.outputIs(pass.name, output)
    output
  }

  private def runOnePass(
    root: PassRoot,
    mkPass: => Pass
  )(using io: PlatformContext): PassOutput = {
    val pass: Pass = mkPass
    Timer.time[PassOutput](pass.name, io.options.showTimes) {
      val parents: ParentStack = ParentStack.empty
      val root1: PassRoot = pass.preProcess(root)
      pass.traverse(root1, parents)
      pass.postProcess(root1)
      pass.close()
      pass.result(root1)
    }
  }
}
