package com.yoppworks.ossum.riddl.translator.graphviz

import java.nio.file.Path

import scala.concurrent.Await
import scala.concurrent.Future
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._
import org.scalatest.matchers.must
import org.scalatest.wordspec.AnyWordSpec

/** Unit Tests For GraphVizAPITest */
class GraphVizAPITest extends AnyWordSpec with must.Matchers {

  private final val binPathForOS: Path = {
    val osName = System.getProperty("os.name").replaceAll("\\s", "")
    osName match {
      case "MacOSX" =>
        Path.of("/usr/local/bin")
      case _ =>
        Path.of("/usr/bin")
    }
  }
  private final val simpleDiagram =
    """graph {
      |    a -- b;
      |    b -- c;
      |    a -- c;
      |    d -- c;
      |    e -- c;
      |    e -- a;
      |}""".stripMargin

  val basicConfig =
    GraphVizAPIConfig().copy(
      dotPath = binPathForOS,
      dotProgramName = dot,
      outputType = svg
    )

  "GraphVizAPITest" should {
    "draw a simple diagram in dot" in {
      val config = basicConfig.copy(dotProgramName = circo, outputType = dot_)
      val graphviz = GraphVizAPI(config)
      graphviz.add(simpleDiagram).addln
      val resultF: Future[(Int, String, String)] = graphviz.runDot
      val result = Await.result(resultF, 1.minute)
      result._1 mustBe 0
      result._3 mustBe empty
      result._2 must startWith("graph {")
    }

    "draw a simple diagram in SVG" in {
      val graphviz = GraphVizAPI(basicConfig)
      graphviz.add(simpleDiagram).addln
      val resultF: Future[(Int, String, String)] = graphviz.runDot
      val result = Await.result(resultF, 1.minute)
      result._1 mustBe 0
      result._3 mustBe empty
      val expected =
        // scalastyle:off
        """<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><!-- Generated by graphviz version 2.43.0 (0) --><!-- Title: %3 Pages: 1 --><svg width="265pt" height="347pt" viewBox="0.00 0.00 199.00 260.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="graph0" class="graph" transform="scale(0.75 0.75) rotate(0) translate(4 256)"><title>%3</title><polygon fill="white" stroke="transparent" points="-4,4 -4,-256 195,-256 195,4 -4,4"/><!-- a --><g id="node1" class="node"><title>a</title><ellipse fill="none" stroke="black" cx="137" cy="-162" rx="27" ry="18"/><text text-anchor="middle" x="137" y="-157.8" font-family="Times,serif" font-size="14.00">a</text></g><!-- b --><g id="node2" class="node"><title>b</title><ellipse fill="none" stroke="black" cx="99" cy="-90" rx="27" ry="18"/><text text-anchor="middle" x="99" y="-85.8" font-family="Times,serif" font-size="14.00">b</text></g><!-- a&#45;&#45;b --><g id="edge1" class="edge"><title>a&#45;&#45;b</title><path fill="none" stroke="black" d="M128.19,-144.76C122.05,-133.46 113.89,-118.44 107.77,-107.15"/></g><!-- c --><g id="node3" class="node"><title>c</title><ellipse fill="none" stroke="black" cx="126" cy="-18" rx="27" ry="18"/><text text-anchor="middle" x="126" y="-13.8" font-family="Times,serif" font-size="14.00">c</text></g><!-- a&#45;&#45;c --><g id="edge3" class="edge"><title>a&#45;&#45;c</title><path fill="none" stroke="black" d="M137.35,-143.89C137.55,-125.94 137.38,-96.92 135,-72 133.85,-59.92 131.54,-46.44 129.56,-36.1"/></g><!-- b&#45;&#45;c --><g id="edge2" class="edge"><title>b&#45;&#45;c</title><path fill="none" stroke="black" d="M105.4,-72.41C109.64,-61.41 115.19,-47.03 119.46,-35.96"/></g><!-- d --><g id="node4" class="node"><title>d</title><ellipse fill="none" stroke="black" cx="27" cy="-90" rx="27" ry="18"/><text text-anchor="middle" x="27" y="-85.8" font-family="Times,serif" font-size="14.00">d</text></g><!-- d&#45;&#45;c --><g id="edge4" class="edge"><title>d&#45;&#45;c</title><path fill="none" stroke="black" d="M45.16,-76.16C63.02,-63.53 90.13,-44.36 107.96,-31.76"/></g><!-- e --><g id="node5" class="node"><title>e</title><ellipse fill="none" stroke="black" cx="164" cy="-234" rx="27" ry="18"/><text text-anchor="middle" x="164" y="-229.8" font-family="Times,serif" font-size="14.00">e</text></g><!-- e&#45;&#45;a --><g id="edge6" class="edge"><title>e&#45;&#45;a</title><path fill="none" stroke="black" d="M157.6,-216.41C153.36,-205.41 147.81,-191.03 143.54,-179.96"/></g><!-- e&#45;&#45;c --><g id="edge5" class="edge"><title>e&#45;&#45;c</title><path fill="none" stroke="black" d="M167.65,-215.91C169.68,-205.57 171.98,-192.09 173,-180 177.12,-131.1 167.62,-117.8 150,-72 145.21,-59.56 138.98,-45.85 134.07,-35.5"/></g></g></svg>"""
      // scalastyle:on
      result._2 mustBe expected

    }
  }
}
