sonar.projectKey=riddl
sonar.organization=ossuminc

sonar.scala.coverage.reportPaths=\
  target/out/jvm/scala-3.9.0-RC6/riddl-commands/scoverage-report/scoverage.xml,\
  target/out/jvm/scala-3.9.0-RC6/riddl-language/scoverage-report/scoverage.xml,\
  target/out/jvm/scala-3.9.0-RC6/riddl-passes/scoverage-report/scoverage.xml,\
  target/out/jvm/scala-3.9.0-RC6/riddl-lib/scoverage-report/scoverage.xml,\
  target/out/jvm/scala-3.9.0-RC6/riddlc/scoverage-report/scoverage.xml,\
  target/out/jvm/scala-3.9.0-RC6/riddl-utils/scoverage-report/scoverage.xml

# Path to sources
#sonar.sources=.
sonar.exclusions=**/src/test/**
#sonar.inclusions=

# Path to tests
#sonar.tests=
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
#sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
