sonar.projectKey=riddl
sonar.organization=ossuminc

sonar.scala.coverage.reportPaths=\
  commands/target/jvm-3/scoverage-report/scoverage.xml,\
  language/target/jvm-3/scoverage-report/scoverage.xml,\
  passes/target/jvm-3/scoverage-report/scoverage.xml,\
  riddlLib/target/jvm-3/scoverage-report/scoverage.xml,\
  riddlc/target/jvm-3/scoverage-report/scoverage.xml,\
  utils/target/jvm-3/scoverage-report/scoverage.xml

# Path to sources
#sonar.sources=.
sonar.exclusions=**/src/test/**
#sonar.inclusions=

# Path to tests
#sonar.tests=
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
#sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
