name: 'get-riddlc'
description: 'Download the riddlc translator'

runs:
  using: "composite"
  steps:
    - name: "Setup JRE"
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: |
        version="0.27.0"
        wget --quiet https://github.com/reactific/riddl/releases/download/${version}/riddlc-${version}.zip
        unzip riddlc-${version}.zip
        export RIDDLC="$(pwd)/riddlc-${version}/bin"
        echo "RIDDLC = ${RIDDLC}"
        echo "$RIDDLC" >> $GITHUB_PATH
        echo GITHUB_PATH = "$GITHUB_PATH"
        echo `which riddlc`
      shell: bash
