/*
 * Copyright 2019-2026 Ossum Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.ossuminc.riddl.passes.diagrams

import com.ossuminc.riddl.language.AST.*
import com.ossuminc.riddl.language.{AST, Contents, Messages, *}
import com.ossuminc.riddl.passes.*
import com.ossuminc.riddl.passes.resolve.ResolutionPass
import com.ossuminc.riddl.passes.symbols.SymbolsPass
import com.ossuminc.riddl.passes.validate.ValidationPass
import com.ossuminc.riddl.utils.PlatformContext

import scala.collection.{immutable, mutable}
import scala.scalajs.js.annotation.*

/** A connection in a data flow diagram representing data flowing through a connector from one
  * streamlet/outlet to another streamlet/inlet
  *
  * @param from
  *   The source definition (outlet's parent streamlet or processor)
  * @param to
  *   The target definition (inlet's parent streamlet or processor)
  * @param connector
  *   The connector element linking them
  * @param messageType
  *   The type name being transmitted
  */
@JSExportTopLevel("DataFlowConnection")
case class DataFlowConnection(
  from: Definition,
  to: Definition,
  connector: Connector,
  messageType: String
)

/** The information needed to generate a Data Flow Diagram. DFDs are generated for each
  * [[com.ossuminc.riddl.language.AST.Context]] and consist of the streaming components that are
  * connected.
  *
  * @param context
  *   The context this diagram represents
  * @param connectors
  *   All connectors within the context
  * @param streamlets
  *   Every PORT-BEARING processor within the context — Adaptor, Context, Entity, Projector,
  *   Repository and Streamlet alike.
  * @param connections
  *   Resolved connection data with source, target, and message type
  *
  * **[4.1], RULED 2026-08-17 by Reid:** `streamlets` means all port-bearing processors, because
  * since the unified processor model every processor may declare portlets — so a diagram drawn from
  * the `Streamlet` case class alone omitted five of the six kinds. This REPLACES the 2026-08-16
  * reading, under which a `portBearing` field was added alongside an unchanged `streamlets`; that
  * field shipped in `2.0.0-rc.15` and is now DELETED rather than left as a synonym.
  *
  * **Breaking**: element type widened from `Streamlet` to `Processor[?]`.
  */
@JSExportTopLevel("DataFlowDiagramData")
case class DataFlowDiagramData(
  context: Context,
  connectors: Seq[Connector] = Seq.empty,
  streamlets: Seq[Processor[?]] = Seq.empty,
  connections: Seq[DataFlowConnection] = Seq.empty
)

/** The information needed to generate a Use Case Diagram. The diagram for a use case is very
  * similar to a Sequence Diagram showing the interactions between involved components of the model.
  */
@JSExportTopLevel("UseCaseDiagramData")
case class UseCaseDiagramData(
  name: String,
  actors: Map[String, Definition],
  interactions: Seq[Interaction]
)

type ContextRelationship = (Context, String)

/** The information needed to generate a Context Diagram showing the relationships between bounded
  * contexts
  *
  * @param domain
  *   The domain or subdomain to which the referent map pertains
  * @param aggregates
  *   The aggregate entities involved in the referent relationships
  * @param relationships
  *   The relationships between contexts
  */
@JSExportTopLevel("ContextDiagramData")
case class ContextDiagramData(
  domain: Domain,
  aggregates: Seq[Entity] = Seq.empty,
  relationships: Seq[ContextRelationship] = Seq.empty
)

/** The information needed to generate a Domain-level diagram showing the domain's structure:
  * processors, subdomains, contexts, and epics
  *
  * @param domain
  *   The domain this diagram represents
  * @param processors
  *   All processors contained in the domain
  * @param subdomains
  *   Nested subdomains
  * @param contexts
  *   Bounded contexts within the domain
  * @param epics
  *   Epics defined in the domain
  */
@JSExportTopLevel("DomainDiagramData")
case class DomainDiagramData(
  domain: Domain,
  processors: Seq[Processor[?]] = Seq.empty,
  subdomains: Seq[Domain] = Seq.empty,
  contexts: Seq[Context] = Seq.empty,
  epics: Seq[Epic] = Seq.empty
)

/** The output of the DiagramsPass encompassing all the generated data for the various diagrams
  *
  * @param messages
  *   The messages generated by this pass
  * @param dataFlowDiagrams
  *   The data necessary for the various data flow diagrams per referent
  * @param useCaseDiagrams
  *   The data necessary for the various use cases defined by
  * @param contextDiagrams
  *   The data necessary for the referent diagrams
  */
@JSExportTopLevel("DiagramsPassOutput")
case class DiagramsPassOutput(
  root: PassRoot = Root.empty,
  messages: Messages.Messages = Messages.empty,
  dataFlowDiagrams: Map[Context, DataFlowDiagramData] = Map.empty,
  useCaseDiagrams: Map[UseCase, UseCaseDiagramData] = Map.empty,
  contextDiagrams: Map[Context, ContextDiagramData] = Map.empty,
  domainDiagrams: Map[Domain, DomainDiagramData] = Map.empty
) extends PassOutput

@JSExportTopLevel("DiagramsPass")
class DiagramsPass(input: PassInput, outputs: PassesOutput)(using PlatformContext)
    extends Pass(input, outputs) {

  def name: String = DiagramsPass.name

  requires(SymbolsPass)
  requires(ResolutionPass)
  requires(ValidationPass)

  private val refMap = outputs.refMap
  private val symTab = outputs.symbols

  private val dataFlowDiagrams: mutable.HashMap[Context, DataFlowDiagramData] =
    mutable.HashMap.empty
  private val useCaseDiagrams: mutable.HashMap[UseCase, UseCaseDiagramData] = mutable.HashMap.empty
  private val contextDiagrams: mutable.HashMap[Context, ContextDiagramData] = mutable.HashMap.empty
  private val domainDiagramsMap: mutable.HashMap[Domain, DomainDiagramData] = mutable.HashMap.empty

  protected def process(definition: RiddlValue, parents: ParentStack): Unit = {
    definition match
      case c: Context =>
        val aggregates = c.entities.filter(_.hasOption("aggregate"))
        val domain = parents.top.asInstanceOf[Domain]
        val root =
          parents.find(c => c.isRootContainer && c.isInstanceOf[Root]).get.asInstanceOf[Root]
        val relationships = makeRelationships(c, root)
        contextDiagrams.put(c, ContextDiagramData(domain, aggregates.toSeq, relationships))
        captureDataFlow(c)
      case d: Domain =>
        captureDomain(d)
      case epic: Epic =>
        epic.cases.foreach { uc =>
          val data = captureUseCase(uc)
          useCaseDiagrams.put(uc, data)
        }

      case _ => ()
  }

  private def makeRelationships(
    context: Context,
    root: Root
  ): immutable.Seq[ContextRelationship] = {
    for {
      processor <- findProcessors(context)
      relationships <- makeProcessorRelationships(context, processor)
    } yield {
      relationships
    }
  }

  private def findProcessors(processor: Processor[?]): immutable.Seq[Processor[?]] = {
    val containedProcessors = processor match {
      case a: Adaptor    => a.contents.processors
      case c: Context    => c.contents.processors
      case e: Entity     => e.contents.processors
      case p: Projector  => p.contents.processors
      case r: Repository => r.contents.processors
      case s: Streamlet  => s.contents.processors
    }
    val includedProcessors = processor.includes.toContents.processors
    val nestedProcessors = (containedProcessors ++ includedProcessors).flatMap(findProcessors)

    includedProcessors ++ nestedProcessors :+ processor
  }

  private def makeProcessorRelationships(
    context: Context,
    processor: Processor[?]
  ): Seq[ContextRelationship] = {
    val rel1 = makeTypeRelationships(context, processor.types.toSeq, processor)
    val rel2 = makeFunctionRelationships(context, processor.functions.toSeq)
    val rel3 = makeHandlerRelationships(context, processor.handlers)
    val rel4 = makeInletRelationships(context, processor.streamlets.flatMap(_.inlets), processor)
    val rel5 = makeOutletRelationships(context, processor.streamlets.flatMap(_.outlets), processor)
    // [2.4] Streamlet → Processor: a processor's OWN ports, hoisted out of the match below.
    // Every Processor has been port-bearing since the unified processor model (`WithInlets` /
    // `WithOutlets` are mixed into the Processor base), but only the `Streamlet` arm looked at
    // them — so a Context, Entity, Projector, Repository or Adaptor declaring its own inlet or
    // outlet contributed no relationship to the diagram.
    //
    // That arm was ALSO dropping half its own work: it called `makeInletRelationships` and then
    // `makeOutletRelationships`, and a block's value is its LAST expression, so the inlet
    // relationships were computed and thrown away. Both defects disappear by asking the question
    // once, of the base trait, rather than per kind.
    val rel6 = makeInletRelationships(context, processor.inlets, processor)
    val rel7 = makeOutletRelationships(context, processor.outlets, processor)
    val rel8 = processor match {
      case a: Adaptor => inferRelationship(context, a)
      case e: Entity  => makeHandlerRelationships(context, e.handlers)
      // Enumerated, not defaulted: these four add nothing BEYOND their ports and handlers, which
      // rel1-rel7 already cover for every kind alike.
      case _: Context    => Seq.empty[ContextRelationship]
      case _: Projector  => Seq.empty[ContextRelationship]
      case _: Repository => Seq.empty[ContextRelationship]
      case _: Streamlet  => Seq.empty[ContextRelationship]
    }
    val result = rel1 ++ rel2 ++ rel3 ++ rel4 ++ rel5 ++ rel6 ++ rel7 ++ rel8
    result.distinct
  }

  private def makeFunctionRelationships(
    context: Context,
    functions: Seq[Function]
  ): Seq[ContextRelationship] = {
    for {
      f <- functions
      // A9: only the deprecated inline Aggregation form carries inline fields for field-level
      // relationships; a TypeRef's fields live in the referenced type.
      inputFields = f.input.collect { case agg: Aggregation => agg.fields }.getOrElse(Seq.empty)
      outputFields = f.output.collect { case agg: Aggregation => agg.fields }.getOrElse(Seq.empty)
      relationship <- makeFieldRelationships(context, inputFields ++ outputFields, f)
    } yield {
      relationship
    }
  }

  private def makeOutletRelationships(
    context: Context,
    outlets: Seq[Outlet],
    parent: Branch[?]
  ): Seq[ContextRelationship] = {
    for {
      o <- outlets
      r = o.type_
      t <- this.refMap.definitionOf[Type](r, parent)
      relationship <- inferRelationship(context, t)
    } yield {
      relationship
    }
  }

  private def makeInletRelationships(
    context: Context,
    inlets: Seq[Inlet],
    parent: Branch[?]
  ): Seq[ContextRelationship] = {
    for {
      i <- inlets
      t = i.type_
      t <- this.refMap.definitionOf[Type](t, parent)
      relationship <- inferRelationship(context, t)
    } yield {
      relationship
    }
  }

  private def makeHandlerRelationships(
    context: Context,
    handlers: Seq[Handler]
  ): Seq[ContextRelationship] = {
    for {
      h <- handlers
      oc: OnClause <- h.clauses if oc.isInstanceOf[OnMessageLikeClause]
      omc: OnMessageLikeClause = oc.asInstanceOf[OnMessageLikeClause]
      relationship <- makeStatementRelationships(context, omc, omc.contents.toSeq)
    } yield {
      relationship
    }
  }

  private def makeStatementRelationships(
    context: Context,
    parent: OnMessageLikeClause,
    statements: Seq[Statements]
  ): Seq[ContextRelationship] = {
    for {
      statement <- statements
      ref <- getStatementReferences(statement)
      definition <- this.refMap.definitionOf[Definition](ref, parent)
      relationship <- inferRelationship(context, definition)
    } yield {
      relationship
    }
  }

  // A54: a widened message/record operand contributes its ref (bare ref, or the constructor's ref).
  private def operandRef(m: MessageRef | RecordRef | Constructor): Reference[Definition] = m match
    case ref: MessageRef => ref
    case ref: RecordRef  => ref
    case c: Constructor =>
      c.ref match
        case r: MessageRef => r
        case r: RecordRef  => r

  // A56 / message-value Task 2: the same, for the widened operand of `tell`/`send`/`yield`/`reply`
  // and of `morph … with`. A ValueRef is not a Reference, so a bound operand yields None rather
  // than being forced into one.
  private def operandRefOpt(
    m: MessageRef | RecordRef | Constructor | ValueRef
  ): Option[Reference[Definition]] = m match
    case _: ValueRef                                   => None
    case other: (MessageRef | RecordRef | Constructor) => Some(operandRef(other))

  private def getStatementReferences(statement: Statements): Seq[Reference[Definition]] = {
    statement match
      // A56: a bound operand (`tell p to …`) contributes no Reference of its own — `p` is a local
      // name, not a reference to a definition. The message it denotes is already reachable through
      // the on-clause that declared it, so the diagram loses nothing by taking only the target.
      case SendStatement(_, msg, portlet)      => operandRefOpt(msg).toSeq :+ portlet
      // A value target names an instance, and a Value is not a Reference, so it contributes none.
      // The diagram loses nothing: the edge it would draw is to the target's KIND, which the
      // enclosing on-clause and the message already place. Enumerated rather than wildcarded.
      case TellStatement(_, msg, target, _) =>
        val targetRef: Seq[Reference[Definition]] = target match
          case pr: ProcessorRef[?] => Seq(pr.asInstanceOf[Reference[Definition]])
          case _: Value            => Seq.empty
        operandRefOpt(msg).toSeq ++ targetRef
      case YieldStatement(_, msg)              => operandRefOpt(msg).toSeq
      case SetStatement(_, field, _)           => Seq(field)
      case MorphStatement(_, entity, state, value) =>
        Seq(entity, state) ++ operandRefOpt(value).toSeq
      case BecomeStatement(_, entity, handler) => Seq(entity, handler)
      case _                                   => Seq.empty
  }

  private def getTypeReferences(typEx: TypeExpression): Seq[Reference[Definition]] = {
    typEx match {
      case EntityReferenceTypeExpression(loc, pid)     => Seq(EntityRef(loc, pid))
      // A `UniqueId` is a reference to an INSTANCE, so a field typed `Id(entity Order)` uses
      // Order exactly as `reference to entity Order` does. Added 2026-08-31 when `reference to`
      // began producing `UniqueId`: without this arm those edges would have vanished silently --
      // no error, just a thinner graph, which is the "collector that stopped one level short"
      // shape this pass has been caught by before.
      //
      // It also turns edges ON for the ~315 pre-existing bare `Id(X)` fields, which had never
      // produced one. That is a deliberate widening, not a side effect: an `Id(entity Order)`
      // field genuinely does reference Order, and its absence from the graph was an oversight of
      // the same family as the report that prompted this.
      case UniqueId(loc, pid, _)                       => Seq(EntityRef(loc, pid))
      case AliasedTypeExpression(loc, keyword, pathId) => Seq(TypeRef(loc, keyword, pathId))
      case aucte: AggregateUseCaseTypeExpression =>
        aucte.fields.foldLeft(Seq.empty) { case (s, f) => s ++ getTypeReferences(f.typeEx) }
      case ate: AggregateTypeExpression =>
        ate.fields.foldLeft(Seq.empty) { case (s, f) => s ++ getTypeReferences(f.typeEx) }
      case _: TypeExpression => Seq.empty
    }
  }

  private def makeTypeRelationships(
    context: Context,
    types: Seq[Type],
    parent: Branch[?]
  ): Seq[ContextRelationship] = {
    for {
      typ <- types
      typEx = typ.typEx
      ref: Reference[Definition] <- getTypeReferences(typEx)
      definition <- refMap.definitionOf[Definition](ref, parent)
      relationship <- inferRelationship(context, definition)
    } yield {
      relationship
    }
  }

  private def makeFieldRelationships(
    context: Context,
    fields: Seq[Field],
    parent: Branch[?]
  ): Seq[ContextRelationship] = {
    for {
      f <- fields
      ref: Reference[Definition] <- getTypeReferences(f.typeEx)
      definition: Definition <- this.refMap.definitionOf[Definition](ref, parent)
      relationship <- inferRelationship(context, definition)
    } yield {
      relationship
    }
  }

  private def inferRelationship(
    context: Context,
    definition: Definition
  ): Option[ContextRelationship] = {
    this.symTab.contextOf(definition) match {
      case Some(foreignContext) =>
        if foreignContext != context then
          definition match {
            case a: Adaptor =>
              refMap.definitionOf[Context](a.referent, a) match {
                case Some(foreignContext) =>
                  if foreignContext != context then
                    Some(foreignContext -> s"Adaptation ${a.direction.format}")
                  else None
                case None => None
              }
            case m: Type         => Some(foreignContext -> s"Uses ${m.identify} from")
            case e: Entity       => Some(foreignContext -> s"References ${e.identify} in")
            case f: Field        => Some(foreignContext -> s"Sets ${f.identify} in")
            case i: Inlet        => Some(foreignContext -> s"Sends to ${i.identify} in")
            case o: Outlet       => Some(foreignContext -> s"Takes from ${o.identify} in")
            case s: Streamlet    => Some(foreignContext -> s"Interacts with ${s.identify} in")
            case p: Processor[?] => Some(foreignContext -> s"Tells to ${p.identify} in")
            case _               => None
          }
        else None
        end if
      case None => None
    }
  }

  private def actorsFirst(a: (String, Definition), b: (String, Definition)): Boolean = {
    a._2 match
      case _: User if b._2.isInstanceOf[User]       => a._1 < b._1
      case _: User                                  => true
      case _: Definition if b._2.isInstanceOf[User] => false
      case _: Definition                            => a._1 < b._1
  }

  /** Collect every [[TwoReferenceInteraction]] of a use case, descending into the
    * [[InteractionContainer]]s (`sequence`, `parallel`, `optional`) that may nest them, and which
    * may nest each other.
    *
    * The recursion is the point: consumers render these diagrams by recursing through the same
    * containers, so a capture that saw only the top level disagreed with the renderer about what a
    * use case contains. A use case whose steps all live inside a `sequence` — the common shape —
    * yielded an actors map that was empty rather than merely incomplete, and an empty map renders
    * as a diagram with no declared participants and no documentation links instead of failing.
    */
  private def twoReferenceInteractionsIn(
    contents: Seq[Interaction | Comment]
  ): Seq[TwoReferenceInteraction] = {
    contents.flatMap {
      case tri: TwoReferenceInteraction => Seq(tri)
      case ic: InteractionContainer     => twoReferenceInteractionsIn(ic.contents.toSeq)
      case _: Interaction | _: Comment | _: Term | _: Description | _: BriefDescription |
          _: AuthorRef =>
        Seq.empty
    }
  }

  private def captureUseCase(uc: UseCase): UseCaseDiagramData = {
    val actors: Map[String, Definition] = {
      twoReferenceInteractionsIn(uc.contents.toSeq)
        .map { tri =>
          val fromDef = refMap.definitionOf[Definition](tri.from.pathId, uc)
          val toDef = refMap.definitionOf[Definition](tri.to.pathId, uc)
          Seq(
            tri.from.pathId.format -> fromDef,
            tri.to.pathId.format -> toDef
          )
        }
        .flatten // get rid of seq of seq
        .filterNot(_._1.isEmpty) // drop empty things
        .map(x => x._1 -> x._2.getOrElse(Root.empty)) // get rid of no definition case
        .distinctBy(_._1) // eliminate duplicates
        .sortWith(actorsFirst) // always list actors first (left side of diagram)
        // An insertion-ordered Map, because a plain `.toMap` DISCARDS the sort above: Scala's
        // Map1..Map4 preserve insertion order only incidentally, and the fifth entry switches to a
        // hash-ordered HashMap. Use cases with five or more actors therefore lost the actors-first
        // ordering silently. `VectorMap` is still a `Map[String, Definition]`, so the type of
        // `UseCaseDiagramData.actors` and its exported signature are unchanged.
        .to(immutable.VectorMap)
    }
    val title = uc.identify + " in " + symTab.parentOf(uc).map(_.identify).getOrElse(" an Epic")
    UseCaseDiagramData(title, actors, uc.contents.filter[Interaction])
  }

  /** The definition a data-flow arrow should attach to for a port: the processor that owns it.
    *
    * [2.4] Streamlet → Processor: this matched the concrete `Streamlet` and otherwise fell back to
    * the PORT itself, so a connector between two Contexts' own ports drew arrows from and to inlets
    * and outlets rather than the processors holding them. Falling back to the port is still right
    * when the owner genuinely is not a processor — it keeps the arrow rather than dropping the
    * connection.
    */
  private def portOwner(portlet: Portlet): Definition =
    symTab.parentOf(portlet).collect { case p: Processor[?] => p: Definition }.getOrElse(portlet)

  private def captureDataFlow(context: Context): Unit = {
    val ctxConnectors = context.connectors.toSeq
    // [4.1]: every PROCESSOR in the context, not only the `Streamlet` case class.
    // `filterThroughWrappers`, not `contents.processors`: the latter is deliberately LITERAL (see
    // its note in Contents.scala), and this must see an included processor exactly as the AST's
    // own `context.streamlets` containment accessor does.
    // [4.1]: `context.streamlets` IS this question now — every contained processor with a
    // non-zero portlet count — so ask the accessor rather than re-deriving it here. The manual
    // `filterThroughWrappers` that stood here was doing the accessor's job while the accessor was
    // still narrow.
    val ctxStreamlets = context.streamlets
    val connections = ctxConnectors.flatMap { connector =>
      if connector.nonEmpty then
        val maybeOutlet = refMap.definitionOf[Outlet](connector.from, context)
        val maybeInlet = refMap.definitionOf[Inlet](connector.to, context)
        (maybeOutlet, maybeInlet) match
          case (Some(outlet), Some(inlet)) =>
            val fromDef: Definition = portOwner(outlet)
            val toDef: Definition = portOwner(inlet)
            val outletParent = symTab
              .parentOf(outlet)
              .collect { case b: Branch[?] =>
                b
              }
              .getOrElse(context)
            val msgTypeName = refMap
              .definitionOf[Type](outlet.type_, outletParent)
              .map(_.identify)
              .getOrElse(outlet.type_.pathId.format)
            Some(DataFlowConnection(fromDef, toDef, connector, msgTypeName))
          case _ => None
      else None
    }
    // A portless `Streamlet` (a stub, or a `void` shape) is NOT a streamlet under [4.1], but it is
    // still a streaming component whose ports are merely unwritten, and a context holding one
    // produced a data flow diagram before this change. Keep it in the GATE so a stub context does
    // not silently lose its diagram — while keeping it out of the DATA, which now answers the
    // portlet question exactly.
    val ctxStreamletStubs =
      context.contents.filterThroughWrappers[Streamlet].filter(_.ports.isEmpty)
    if ctxConnectors.nonEmpty || ctxStreamlets.nonEmpty || ctxStreamletStubs.nonEmpty then
      dataFlowDiagrams.put(
        context,
        DataFlowDiagramData(context, ctxConnectors, ctxStreamlets, connections)
      )
  }

  private def captureDomain(domain: Domain): Unit = {
    val processors = domain.contents.processors.toSeq
    val subdomains = domain.domains.toSeq
    val contexts = domain.contexts.toSeq
    val epics = domain.epics.toSeq
    domainDiagramsMap.put(
      domain,
      DomainDiagramData(domain, processors, subdomains, contexts, epics)
    )
  }

  def result(root: PassRoot): DiagramsPassOutput = {
    DiagramsPassOutput(
      root,
      messages.toMessages,
      dataFlowDiagrams.toMap,
      useCaseDiagrams.toMap,
      contextDiagrams.toMap,
      domainDiagramsMap.toMap
    )
  }
}

@JSExportTopLevel("DiagramsPass$")
object DiagramsPass extends PassInfo[PassOptions] {
  val name: String = "Diagrams"
  def creator(options: PassOptions = PassOptions.empty)(using PlatformContext): PassCreator = {
    (in: PassInput, out: PassesOutput) =>
      DiagramsPass(in, out)
  }
}
