/*
 * Copyright 2019-2026 Ossum Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.ossuminc.riddl.language.parsing

import com.ossuminc.riddl.utils.{ExceptionUtils, CommonOptions}
import com.ossuminc.riddl.language.AST.*
import com.ossuminc.riddl.language.{Contents, *}
import com.ossuminc.riddl.language.Messages
import com.ossuminc.riddl.language.At
import fastparse.Parsed.{Failure, Success}
import fastparse.internal.Lazy
import fastparse.*

import java.nio.file.Path
import java.util.concurrent.{ExecutorService, Executors}
import java.util.concurrent.atomic.AtomicReference
import scala.annotation.unused
import scala.collection.mutable
import scala.concurrent.{ExecutionContext, Future}
import scala.util.control.NonFatal

/** A trait for tracking errors generated by fastparse */
trait ParsingErrors {

  private val messages: mutable.ListBuffer[Messages.Message] =
    mutable.ListBuffer.empty[Messages.Message]

  protected def messagesNonEmpty: Boolean = synchronized { messages.nonEmpty }

  /** True iff any accumulated message is error-severity. A successful fastparse that only
    * accumulated warnings/deprecations should NOT be treated as a failure — only error-level
    * messages indicate the parse should be abandoned.
    */
  protected def messagesHaveErrors: Boolean = synchronized { messages.exists(_.isError) }

  private def addMessage(message: Messages.Message): Unit = {
    synchronized {
      messages.append(message)
    }
  }

  protected def messagesAsList: Messages.Messages = {
    synchronized { messages.toList }
  }

  /** The accumulated non-fatal (and fatal) messages produced during a parse. Unlike a fastparse
    * failure, a *successful* parse can still accumulate warnings/deprecations; this accessor lets
    * callers retrieve them so they can be surfaced alongside the parsed Root.
    */
  def accumulatedMessages: Messages.Messages = messagesAsList

  def error(loc: At, message: String, context: String = ""): Unit = {
    val msg = Messages.Message(loc, message, Messages.Error, context)
    addMessage(msg)
  }

  def warning(loc: At, message: String, context: String = ""): Unit = {
    val msg = Messages.Message(loc, message, Messages.Warning, context)
    addMessage(msg)
  }

  /** Emit a deprecation.
    *
    * `code` should come from [[com.ossuminc.riddl.language.RuleId]] so tools can group and count
    * without regex-matching the prose, and `autoFixable` should be true only when `prettify`
    * rewrites the construct with no human decision required.
    */
  def deprecation(
    loc: At,
    message: String,
    context: String = "",
    code: Option[RuleId] = None,
    autoFixable: Boolean = false
  ): Unit = {
    val msg = Messages.Message(loc, message, Messages.Deprecation, context, "", code, autoFixable)
    addMessage(msg)
  }

  private def mkTerminals(list: List[Lazy[String]]): String = {
    list
      .map(_.force)
      .map {
        case s: String if s.startsWith("char-pred")  => "pattern"
        case s: String if s.startsWith("chars-with") => "pattern"
        case s: String if s == "fail"                => "whitespace after keyword"
        case s: String                               => s
      }
      .distinct
      .sorted
      .mkString("(", " | ", ")")
  }

  /** When a parse failure occurs, the failure index points to where fastparse found the unexpected
    * token (the "next" token). For better UX, we want to point to where the expected token was
    * missing — just after the last successfully consumed token. Only adjust if the next token is on
    * a different line (crossing a newline), which is the case that confuses users the most.
    */
  private def adjustFailureIndex(index: Int, input: RiddlParserInput): Int =
    val data = input.data
    if index <= 0 || index > data.length then index
    else
      var i = index - 1
      // Walk backward past whitespace
      while i >= 0 && data(i).isWhitespace do i -= 1
      // Only adjust if we crossed a newline
      if i >= 0 && input.lineOf(i) < input.lineOf(index.min(data.length - 1)) then
        i + 1 // Just after last non-whitespace char
      else index // Same line — keep original
    end if
  end adjustFailureIndex

  def makeParseFailureError(failure: Failure, input: RiddlParserInput): Unit = {
    val adjustedIndex = adjustFailureIndex(failure.index, input)
    val location = input.location(adjustedIndex)
    val trace = failure.trace()
    val msg = trace.terminals.value.size match {
      case 0 => "Expected nothing"
      case 1 => s"Expected " + mkTerminals(trace.terminals.value)
      case _ => s"Expected one of " + mkTerminals(trace.terminals.value)
    }
    val context = trace.groups.render
    error(location, msg, context)
  }

  def makeParseFailureError(
    exception: Throwable,
    loc: At = At.empty,
    context: String = ""
  ): Unit = {
    val message = ExceptionUtils.getRootCauseStackTrace(exception).mkString("\n", "\n  ", "\n")
    error(loc, message, context)
  }
}
