name: Vale Linting

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - doc/src/hugo/content/**
      - .github/workflows/vale-linting.yml

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Vale
        uses: errata-ai/vale-action@master
        with:
          files: doc/src/hugo/content
          fail_on_error: true
          filter_mode: nofilter
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
